name: Build and test
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: yarn lint
      - run: yarn ts
      - run: yarn test
      - run: yarn coveralls
